# Generated by Django 4.1.2 on 2022-10-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Delhi', 'Delhi')], max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('job_city', models.CharField(max_length=100)),
                ('profile_image', models.CharField(max_length=100)),
                ('my_file', models.CharField(max_length=100)),
            ],
        ),
    ]
